### ISSUE TITLE
Race In Steve's services pkg

### ISSUE THREAD

**Issue by mikeynap** [sigma-dev/sigma#105]
```
Write at 0x00c42038aeb8 by goroutine 38:
  github.com/sigma-dev/sigma/cmd.sigmaRun.func2()
      /Users/mnapolit/go/src/github.com/sigma-dev/sigma/cmd/sigma.go:135 +0x10f
```

It happens on Kill(). Calling Kill() sets sg.forceQuit = true, but something can read from it at the same time.

On service.Kill()
helper.go:74, helper.go:42

If Steve's service polls in a thread called "A". "A" checks for forceQuit == true at every tick.
Then a goroutine B() calls "service.Kill()" Kill sets forceQuit = true.

Bam. DaterzRace.

**Comment by stephenrlouie** [comment]
I realized this during development, I decided to not take on the locking overhead since there is one routine reading every N seconds and only one writer. At worst right now you have to wait another N seconds, because you "just" missed the update of the bool, but will catch it on the next ticker. 

If there were multiple threads that could update the value I would definitely need locks. I think its ok in this instance since I'm currently forcing only one potential writer. 

Closing this....
