### ISSUE TITLE
Add Requires/Wants/After/Before for Service ordering

### ISSUE THREAD

**Issue by adamschaub** [sigma-dev/sigma#31]
Ordering Service creation by input -> output dependency may be insufficient or too clunky to express some service dependencies.

For instance, a service is not reliant on any other service's output for configuration/deployment purposes, but is dependent on another service to operate properly (host has an sshd running, for example). You would want to delay the creation of the service by expressing it's dependency with an `After` and `Requires` relationship to ensure other required services are started beforehand. 

In some cases, we'll want to trigger the deployment of required services when a request to deploy a child service is given.

@mcaulfield lmk what you think

**Comment by stephenrlouie** [comment]
RN we would make a service reliant on some other services output, which could be like isReady. or something of that sort. Which would indicate services using that as input that it has reached some valid enough state.

Aren't we essentially implying an "After" since we only can receive outputs if the service is running and active.

**Comment by adamschaub** [comment]
We are implying After right now in this context. My point is, there are cases where supplied inputs may not reflect the real dependencies. In those cases, without additional options for specifying extra dependencies, users will have to shoe-horn artificial outputs/inputs for services just to enforce order.

**Comment by mcaulfield** [comment]
Too complex.
